### ISSUE TITLE
How to use this with older version of spaCy?

### ISSUE THREAD

**Issue by ksjae** [MartinoMensio/spacy-universal-sentence-encoder#7]
pip seems to install newer version of spaCy(2.3.1), but I need to use 2.1.x for other pipeline utilities(neuralconf by HF).
However, requirements.txt doesn't list spacy.

Is this package built specifically for spacy>=2.3 or is it just configured to do so?

**Comment by MartinoMensio** [comment]
Hi @ksjae,
I was requesting `spacy>=2.3` because they changed something in the logging (see https://github.com/MartinoMensio/spacy-universal-sentence-encoder/issues/5) but I didn't realise that the change I made is also backwards compatible.

Therefore I just released v0.3.1 both here and on pip, so just install the update with `pip install spacy_universal_sentence_encoder==0.3.1`

In this way it should use the already installed spacy library because compatible with the requirements https://github.com/MartinoMensio/spacy-universal-sentence-encoder/blob/master/setup.cfg#L14
